environments:
  swarmspawner:
    environment_variables:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: '{{SECRET:[jhub_swarmspawner][username]}}'
      PYPI_PASSWORD: '{{SECRET:[jhub_swarmspawner][password]}}'
    pipelines:
      - swarmspawner
      - swarmspawner_accelerator_selection
pipelines:
  swarmspawner:
    group: bare_metal_pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      swarmspawner_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/SwarmSpawner.git
        branch: master
        destination: swarmspawner
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: swarmspawner
      TEST_DIRECTORY: swarmspawner
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package
  swarmspawner_accelerator_selection:
    group: bare_metal_pypi_package
    locking: off
    materials:
      swarmspawner_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/SwarmSpawner.git
        branch: accelerator_selection
        destination: swarmspawner_accelerator_selection
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: swarmspawner_accelerator_selection
      TEST_DIRECTORY: swarmspawner_accelerator_selection
      PUSH_DIRECTORY: publish-python-scripts
    template: bare_metal_pypi_package